/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class glboy_AndroPlayer */

#ifndef _Included_glboy_AndroPlayer
#define _Included_glboy_AndroPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     glboy_AndroPlayer
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_glboy_AndroPlayer_init
  (JNIEnv *, jclass);

/*
 * Class:     glboy_AndroPlayer
 * Method:    resize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_glboy_AndroPlayer_resize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     glboy_AndroPlayer
 * Method:    render
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_glboy_AndroPlayer_render
  (JNIEnv *, jclass);

/*
 * Class:     glboy_AndroPlayer
 * Method:    touch
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_glboy_AndroPlayer_touch
  (JNIEnv *, jclass, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
